name: CI
on:
  push:
    branches: ["main"]
permissions:
  id-token: write
  contents: read
jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0

      - name: dotnet test
        run: dotnet test --configuration Release

      - name: dotnet publish
        run: dotnet publish src/GitHubActionsDotNet.Api/GitHubActionsDotNet.Api.csproj --configuration Release -o artifacts

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: action-artifact
          path: artifacts/

  Deploy_dev:
    needs: build
    uses: ./.github/workflows/deploy.yml
    with: 
      environment-name: dev
    secrets:
     AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
     AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
     AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID}}
     AZURE_APP_NAME: ${{ secrets.AZURE_APP_NAME }}
     
  Deploy_pro:
    needs: Deploy_dev
    uses: ./.github/workflows/deploy.yml
    with: 
      environment-name: pro
    secrets:
     AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
     AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
     AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID}}
     AZURE_APP_NAME: ${{ secrets.AZURE_APP_NAME }}
